### ISSUE TITLE
UI horizontal scroll 

### ISSUE THREAD

**Issue by hishamkaram** [mkdocs/mkdocs-bootswatch#25]
![screenshot from 2017-02-23 13-43-06](https://cloud.githubusercontent.com/assets/24391550/23257814/17afe674-f9ce-11e6-8b98-67572c56d2e0.png)

**Comment by juzraai** [comment]
Maybe you can use one [fenced code block](http://www.mkdocs.org/user-guide/writing-your-docs/#fenced-code-blocks) instead of those list of inline code snippets. Code blocks have their own horizontal scrollbar so they won't screw up the page structure.

Also you can use line breaks in those commands to make them shorter.

Example:

```
cmd1 arg1
cmd2 \
   arg1 \
   arg2
cmd 3
```

Plus, this way all commands can be copied at once - while those $-prefixed lines aren't. ;)

**Comment by hishamkaram** [comment]
@juzraai Thank you
