### ISSUE TITLE
Adapt new bootswatch theme for mkdocs

### ISSUE THREAD

**Issue by ejm714** [mkdocs/mkdocs-bootswatch#52]
What are the steps for adapting a new bootswatch theme for mkdocs given the recent version bump of mkdocs-bootswatch? I'd like to use lux and would be happy to create a PR with this addition.

I've tried creating a `custom_dir` folder which includes the `bootstrap-custom.min.css` file for lux. However, when the page renders, the navigation bar sits on top of the main content.

**Comment by jimporter** [comment]
With MkDocs 1.0.x, it's not easy to use a Bootswatch 4 theme, since the base theme uses Bootswatch 3 (or maybe 2?). However, MkDocs 1.1 will use Bootswatch 4, making this a lot easier. With that and my forthcoming changes for #56, you should be able to just copy an existing `mkdocs-bootswatch` theme, drop in the relevant `bootstrap.min.css` file, and then fix up the theme-specific CSS in `css/base.css`. Themes can also benefit from setting `hljs_style` in `mkdocs_theme.yml`.

For `lux` in particular, this project will support that theme natively once my changes for #56 land.

**Comment by jimporter** [comment]
`lux` is supported as of a72001a48c14a4a9bc176df49a06f4f217fae184. I guess this could be considered "resolved", or maybe it makes sense to add more docs about how to make a new derived theme...
